site_name: cfgov-refresh
pages:
- Introduction: index.md
- Installation: installation.md
- Usage: usage.md
- Building and Deploying for cf.gov:
    - New projects: new-projects.md
    - Branching and merging: branching-merging.md
    - Feature flags: feature-flags.md
    - Split testing: split-testing.md
    - How we use Travis CI: travis.md
- Back-end guidelines:
    - Wagtail and Django migrations: wagtail-migrations.md
    - Wagtail Pages vs Django views: django-to-wagtail.md
    - Forms in Wagtail page context: forms-in-wagtail.md
    - Testing: testing-be.md
    - Translation: translation.md
    - Caching: caching.md
- Front-end guidelines:
    - Atomic structure and design: atomic-structure.md
    - Testing: testing-fe.md
- Development tips: development-tips.md
- APIs:
    - Ask CFPB: ask-cfpb.md
    - Consumer complaints: consumer-complaint-database.md
    - HMDA data: hmda.md

theme:
  name: 'readthedocs'
extra_css:
    - css/overrides.css

markdown_extensions:
    - admonition
    - pymdownx.betterem
    - pymdownx.magiclink
    - pymdownx.superfences
    - pymdownx.tilde
    - tables
    - toc:
        permalink: "Â¶"
