site_name: cfgov-refresh

repo_url: https://github.com/cfpb/cfgov-refresh

nav:
- Introduction: index.md
- Installation: installation.md
- Usage: usage.md
- Pages and Components:
    - Atomic structure and design: atomic-structure.md
    - Creating and editing components: editing-components.md
    - Django and Wagtail migrations: migrations.md
    - Forms in Wagtail page context: forms-in-wagtail.md
    - Wagtail pages: wagtail-pages.md
- Supporting Features:
    - Caching: caching.md
    - Feature flags: feature-flags.md
    - Satellite repos: satellite-repos.md
    - Split testing: split-testing.md
    - Translation: translation.md
- Testing:
    - Browser Testing: testing-fe.md
    - JavaScript Unit Testing: javascript-unit-tests.md
    - Python Unit Testing: testing-be.md
- Contributing:
    - Branching and merging: branching-merging.md
    - Contributing to the docs: contributing-docs.md
    - Development tips: development-tips.md
    - How we use Travis CI: travis.md
- Public APIs and Data:
    - Ask CFPB: ask-cfpb.md
    - Consumer complaints: consumer-complaint-database.md
    - Find a housing counselor tool: housing-counselor-tool.md
    - HMDA data: hmda.md

theme:
    name: readthedocs
    custom_dir: docs/theme-overrides/ # @TODO: We may be able to remove this custom template when MkDocs 1.1 is released
extra_css:
    - css/overrides.css

markdown_extensions:
    - admonition
    - pymdownx.betterem
    - pymdownx.highlight
    - pymdownx.magiclink
    - pymdownx.superfences
    - pymdownx.tilde
    - tables
    - toc:
        permalink: "Â¶"
