{{- range .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cfgov.fullname" $ | lower }}-cronjob-{{ .name | lower }}
  labels:
    {{- include "cfgov.labels" $ | nindent 4 }}
spec:
  suspend: {{ default false .suspend }}
  schedule: {{ default "@daily" .schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          containers:
            - name: {{ $.Chart.Name | lower }}-cronjob-{{ .name | lower }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
                {{- range .command }}
                - {{ . | quote }}
                {{- end }}
              args:
                {{- range .args }}
                - {{ . | quote }}
                {{- end }}
              volumeMounts:
                # Add in main container volumes
                {{- range $.Values.volumes }}
                - mountPath: {{ .mountPath }}
                  name: {{ .name }}
                {{- end }}
                # Add in the cronjob volumes
                {{- range .volumes }}
                - mountPath: {{ .mountPath }}
                  name: {{ .name }}
                {{- end }}
              env:
                {{- include "cfgov.postgresEnv" $ | nindent 16}}
                {{- if $.Values.elasticsearch.enabled }}
                - name: ES_HOST
                  {{- if $.Values.elasticsearch.nameOverride }}
                  value: "{{ $.Values.elasticsearch.nameOverride }}-master"
                  {{- else if $.Values.elasticsearch.fullnameOverride }}
                  value: {{ $.Values.elasticsearch.fullnameOverride | quote }}
                  {{- else }}
                  value: elasticsearch-master
                  {{- end }}
                {{- end }}
                {{- range $.Values.extraEnvs }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
                {{- end }}
          restartPolicy: {{ default "OnFailure" .restartPolicy }}
          volumes:
            # Add in main container volumes
            {{- range $.Values.volumes }}
            - name: {{ .name }}
              {{- toYaml .volume | nindent 14 }}
            {{- end }}
            # Add in cronjob volumes
            {{- range .volumes }}
            - name: {{ .name }}
              {{- toYaml .volume | nindent 14 }}
            {{- end }}
{{- end }}
