{{- range .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cfgov.fullname" $ | lower }}-cronjob-{{ .name | lower }}
  labels:
    {{- include "cfgov.labels" $ | nindent 4 }}
spec:
  suspend: {{ default false .suspend }}
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          containers:
            - name: {{ $.Chart.Name | lower }}-cronjob-{{ .name | lower }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
                {{- range .command }}
                - {{ . | quote }}
                {{- end }}
              args:
                {{- range .args }}
                - {{ . | quote }}
                {{- end }}
              volumeMounts:
                {{- range $.Values.volumes }}
                - mountPath: {{  .mountPath }}
                  name: {{ .name }}
                {{- end }}
              env:
                - name: CFGOV_SCHEMA
                  value: "http"
                - name: CFGOV_HOST
                  value: {{ include "cfgov.fullname" $ | trunc 63 | trimSuffix "-" }}
                - name: CFGOV_PORT
                  value: {{ $.Values.service.port | quote }}
                {{- if $.Values.postgresql.enabled }}
                - name: PGHOST
                  {{- if $.Values.postgresql.nameOverride }}
                  value: "{{ $.Values.postgresql.nameOverride }}-postgresql"
                  {{- else if $.Values.postgresql.fullnameOverride }}
                  value: "{{ $.Values.postgresql.fullNameOverride }}"
                  {{- else }}
                  value: "{{ include "cfgov.fullname" $ }}-postgresql"
                  {{- end }}
                - name: PGUSER
                  value: "{{ $.Values.postgresql.postgresqlUsername }}"
                - name: PGPASSWORD
                  value: "{{ $.Values.postgresql.postgresqlPassword }}"
                - name: PGDATABASE
                  value: "{{ $.Values.postgresql.postgresqlDatabase }}"
                - name: DATABASE_URL
                  {{- if $.Values.postgresql.nameOverride }}
                  value: "postgres://{{ $.Values.postgresql.postgresqlUsername }}:{{ $.Values.postgresql.postgresqlPassword }}@{{ $.Values.postgresql.nameOverride }}-postgresql/{{ $.Values.postgresql.postgresqlDatabase }}"
                  {{- else if $.Values.postgresql.fullnameOverride }}
                  value: "postgres://{{ $.Values.postgresql.postgresqlUsername }}:{{ $.Values.postgresql.postgresqlPassword }}@{{ $.Values.postgresql.fullNameOverride }}/{{ $.Values.postgresql.postgresqlDatabase }}"
                  {{- else }}
                  value: "postgres://{{ $.Values.postgresql.postgresqlUsername }}:{{ $.Values.postgresql.postgresqlPassword }}@{{ include "cfgov.fullname" $ }}-postgresql/{{ $.Values.postgresql.postgresqlDatabase }}"
                  {{- end }}
                {{- end }}
                {{- if $.Values.elasticsearch.enabled }}
                - name: ES_HOST
                  {{- if $.Values.elasticsearch.nameOverride }}
                  value: "{{ $.Values.elasticsearch.nameOverride }}-master"
                  {{- else if $.Values.elasticsearch.fullnameOverride }}
                  value: {{ $.Values.elasticsearch.fullnameOverride | quote }}
                  {{- else }}
                  value: elasticsearch-master
                  {{- end }}
                {{- end }}
                {{- range $.Values.extraEnvs }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
                {{- end }}
          restartPolicy: {{ .restartPolicy }}
          volumes:
            {{- range $.Values.volumes }}
            - name: {{ .name }}
              {{- toYaml .volume | nindent 14 }}
            {{- end }}
{{- end }}
