# Install a role from the Ansible Galaxy
- src: geerlingguy.mysql

- src: geerlingguy.git

- src: geerlingguy.firewall

- src: https://github.com/Ken24/ansible-role-python.git
  version: master
  name: Ken24.python

- src: https://github.com/vccabral/ansible-role-elasticsearch.git
  version: master
  name: vccabral.elasticsearch
