name: docker

on: pull_request

env:
  TEST_TAG: cfpb/consumerfinancegov:test

jobs:

  root_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            docker:
              - '**.py'
              - 'requirements/**.txt'
              - '**.html'
              - '**.mo'
              - '**.po'
              - '**Dockerfile'
              - '**.conf'
              - '**.csv'

      - name: Setup QEMU
        if: steps.filter.outputs.docker == 'true'
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        if: steps.filter.outputs.docker == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Build base Docker and export to Docker (not DockerHub)
        if: steps.filter.outputs.docker == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tag: ${{ env.TEST_TAG }}
          build-args: FRONTEND_TARGET=ci

  zip_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            docker:
              - '**.py'
              - 'requirements/**.txt'
              - '**.html'
              - '**.mo'
              - '**.po'
              - '**.conf'
              - 'docker/deployable-zipfile/Dockerfile'

      - name: Setup QEMU
        if: steps.filter.outputs.docker == 'true'
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        if: steps.filter.outputs.docker == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Build zipfile and export to Docker (not DockerHub)
        if: steps.filter.outputs.docker == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./docker/deployable-zipfile/
          load: true
          tag: ${{ env.TEST_TAG }}
          build-args: FRONTEND_TARGET=ci
  docs_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            docker:
              - '**.py'
              - 'requirements/**.txt'
              - '**.html'
              - '**.mo'
              - '**.po'
              - '**.conf'
              - '**.csv'
              - 'docker/docs/Dockerfile

      - name: Setup QEMU
        if: steps.filter.outputs.docker == 'true'
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        if: steps.filter.outputs.docker == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Build docs and export to Docker (not DockerHub)
        if: steps.filter.outputs.docker == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./docker/docs/
          load: true
          tag: ${{ env.TEST_TAG }}
          build-args: FRONTEND_TARGET=ci