### POSTGRESQL OVERRIDES ###
postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: cfpb  # Admin password, admin user is postgres
    password: cfpb  # User password
    username: cfpb  # User username
    database: cfgov
  primary:
    persistence:
      enabled: false
    service:
      type: ClusterIP

### ELASTICSEARCH OVERRIDES ###
elasticsearch:
  enabled: true

  # Disable persistence for local by default
  persistence:
    enabled: false

  replicas: 2
  minimumMasterNodes: 0
  antiAffinity: "soft"

  # Shrink default JVM heap.
  esJavaOpts: "-Xmx512m -Xms512m"

  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "1024M"
    limits:
      cpu: "1000m"
      memory: "2048M"

  # Request smaller persistent volumes, if enabled.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "hostpath"
    resources:
      requests:
        storage: 100M

  service:
    type: ClusterIP

### KIBANA OVERRIDES ###
kibana:
  enabled: true

  persistence:
    enabled: false

  service:
    type: ClusterIP
